"use client";
import Navbars from "@/components/Navbars";
import "./globals.css";
import type { Metadata } from "next";

import { createContext, useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const AppContext = createContext<any>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [account, setAccount] = useState<string>("");
  return (
    <html lang="en">
      <body className="relative">
        <AppContext.Provider value={{ account, setAccount }}>
          <Navbars />
          {children}
        </AppContext.Provider>
      </body>
    </html>
  );
}
